<?xml version="1.0" encoding="utf-8"?><Database Name="AniClubWebSecurity" Class="userssDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MACHINE-20\SQLEXPRESS;Initial Catalog=AniClubWebSecurity;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AniClubWebSecurityConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="passvord" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>